permissions:
  id-token: write
  contents: read

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:

      - name: Debug OIDC claims
        shell: bash
        run: |
          TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{
            sub,
            aud,
            repository,
            repository_owner,
            ref,
            event_name,
            environment
          }'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 buckets
        run: aws s3 ls